#!/usr/bin/env python3
"""Emit part2_projects.json with translations for 14 remaining flyer projects."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).parent / "part2_projects.json"

PROJECTS: dict[str, dict[str, str]] = {
    "cleantric": {
        "Alitec's Cleaning Service Company solution on Odoo helps cleaning operators manage the full booking lifecycle, from website enquiry and cleaner selection to repeat sessions, appointment slots, address capture, portal follow-up, sales orders, and payment continuity.":
            "Alitec 清洁服务公司 Odoo 方案帮助清洁运营商管理完整预约生命周期，从网站咨询与保洁员选择到重复服务、预约时段、地址采集、门户跟进、销售订单与支付延续。",
        "Alitec's Cleaning Service Company solution on Odoo helps cleaning\n        operators manage the full booking lifecycle, from website enquiry and\n        cleaner selection to repeat sessions, appointment slots, address\n        capture, portal follow-up, sales orders, and payment continuity.":
            "Alitec 清洁服务公司 Odoo 方案帮助清洁运营商管理完整预约生命周期，从网站咨询与保洁员选择到重复服务、预约时段、地址采集、门户跟进、销售订单与支付延续。",
        "Cleaning Service<br />Company": "清洁服务<br />公司",
        "Cleaning Service": "清洁服务",
        "Address<br />Start": "地址<br />开始",
        "Select<br />Service": "选择<br />服务",
        "Choose<br />Cleaner": "选择<br />保洁员",
        "Find &amp;<br />Confirm Slot": "查找并<br />确认时段",
        "Review &amp;<br />Pay": "确认并<br />支付",
        "Complete Cleaning Booking Solutions with Odoo": "完整清洁预约 Odoo 方案",
        "Cleaning Booking Workflow": "清洁预约工作流",
        "One-Time": "单次",
        "Repeat Sessions": "重复服务",
        "Any Cleaner": "任意保洁员",
        "Preferred Helper": "指定保洁员",
        "Saved Address": "已存地址",
        "Service Types": "服务类型",
        "Active Cleaners": "在岗保洁员",
        "Online Bookings": "在线预约",
        "Future Slots": "未来时段",
        "Payment Ready": "待支付",
        "Booking Type Overview": "预约类型概览",
        "Monthly Booking Volume": "月度预约量",
        "Service Type Mix": "服务类型构成",
        "Jobs Scheduled Today": "今日排程工单",
        "Address-First": "地址优先",
        "Start the booking flow from service address or postal details.": "从服务地址或邮编开始预约流程。",
        "Cleaner Choice": "保洁员选择",
        "Support preferred-cleaner requests or any available cleaner.": "支持指定保洁员或任意可用保洁员。",
        "Accurate Slots": "精准时段",
        "Search service windows from real calendars, duration, and availability.": "基于真实日历、时长与可用性搜索服务窗口。",
        "Payment-Ready": "支付就绪",
        "Carry bookings forward into order review, portal follow-up, and payment.": "预约延续至订单确认、门户跟进与支付。",
        "Website Booking Journey": "网站预约旅程",
        "Guide customers through a structured self-service cleaning reservation flow.": "引导客户完成结构化自助清洁预约流程。",
        "Service Catalog &amp; Options": "服务目录与选项",
        "Offer service types, session counts, and repeat-cleaning choices clearly.": "清晰展示服务类型、次数与重复清洁选项。",
        "Cleaner Matching": "保洁员匹配",
        "Match bookings to a selected helper or the next available resource.": "将预约匹配至指定或下一可用保洁员。",
        "Slot Search &amp; Scheduling": "时段搜索与排程",
        "Generate time slots from calendars, service duration, and actual availability.": "基于日历、服务时长与实际可用性生成时段。",
        "Address Book Control": "地址簿管控",
        "Save service locations, contact names, phones, and postal details before confirmation.": "确认前保存服务地点、联系人、电话与邮编。",
        "Sales &amp; Payment Continuity": "销售与支付延续",
        "Carry the booking into orders, payment status, and invoice-ready follow-through.": "预约延续至订单、支付状态与可开票跟进。",
        "Portal Follow-Up": "门户跟进",
        "Give customers a cleaner portal experience after booking and confirmation.": "预约确认后提供清晰的客户门户体验。",
        "Gateway Integration": "支付网关集成",
        "Support local payment-provider flows such as HitPay and related online checkout options.": "支持 HitPay 等本地支付网关与在线结账。",
        "Address": "地址",
        "Start": "开始",
        "Enter service address or postal code first": "先输入服务地址或邮编",
        "Select": "选择",
        "Service": "服务",
        "Choose service type and package or sessions": "选择服务类型、套餐或次数",
        "Choose": "选择",
        "Cleaner": "保洁员",
        "Pick a helper or request any available cleaner": "选择保洁员或请求任意可用人员",
        "Find &amp;": "查找并",
        "Confirm Slot": "确认时段",
        "Search dates and confirm available appointment windows": "搜索日期并确认可用预约窗口",
        "Review &amp;": "确认并",
        "Pay": "支付",
        "Continue to order review, portal follow-up, and payment": "继续订单确认、门户跟进与支付",
        "Single cleaning appointments on demand": "按需单次清洁预约",
        "Session-based cleaning packages": "按次清洁套餐",
        "Auto-match by available resource": "按可用资源自动匹配",
        "Support customer helper preference": "支持客户指定保洁员",
        "Reuse stored service-location details": "复用已存服务地点信息",
        "Postal-code booking start": "邮编起始预约",
        "Session package control": "次数套餐管控",
        "Customer contact capture": "客户联系信息采集",
        "Booking summary review": "预约摘要确认",
        "Calendar-based slot logic": "基于日历的时段逻辑",
        "Custom sales or invoice print": "定制销售或发票打印",
        "Payment status visibility": "支付状态可视化",
        "Portal and order continuity": "门户与订单延续",
        "Repeat Cleaning (194) 61%": "重复清洁 (194) 61%",
        "One-Time Service (124) 39%": "单次服务 (124) 39%",
        "Residential Cleaning": "住宅清洁",
        "Deep Cleaning": "深度清洁",
        "Weekly Package": "周套餐",
        "Move-Out Service": "搬出清洁",
        "CL-2842": "CL-2842",
        "Tower A": "A 座",
        "CL-2847": "CL-2847",
        "Factory": "工厂",
        "CL-2851": "CL-2851",
        "Mall B": "B 商场",
        "CL-2854": "CL-2854",
        "Unit 5C": "5C 单元",
        "Faster Self-Service Booking": "更快自助预约",
        "Reduce manual back-and-forth by letting customers start and complete bookings online.": "客户在线完成预约，减少人工往返。",
        "Better Cleaner Utilization": "更优保洁员利用率",
        "Match real helper availability to service demand and repeat-session planning.": "将真实可用性与服务需求及重复服务计划匹配。",
        "Cleaner Order Continuity": "清洁订单延续",
        "Keep address, slot, order, and payment details connected across the full flow.": "地址、时段、订单与支付全链路贯通。",
        "Smoother Customer Experience": "更顺畅客户体验",
        "Give customers clearer scheduling, saved addresses, and better follow-up after confirmation.": "提供更清晰排程、地址保存与确认后跟进。",
    },
    "public-safety": {
        "Alitec's Public Safety and Firefighting Equipment Manufacturing solution on Odoo helps manufacturers and service teams manage the full lifecycle, from sales demand and BOM planning to shop-floor production, QC, serial traceability, field service, invoicing, and compliance documents.":
            "Alitec 公共安全与消防设备制造 Odoo 方案帮助制造商与服务团队管理全生命周期，从销售需求与 BOM 计划到车间生产、质检、序列号追溯、现场服务、开票与合规文档。",
        "Public Safety<br />Equipment": "公共安全<br />设备",
        "Public Safety": "公共安全",
        "Equipment": "设备",
        "Sales<br />Demand": "销售<br />需求",
        "BOM &amp;<br />Planning": "BOM<br />与计划",
        "Shop Floor<br />Production": "车间<br />生产",
        "Serial &amp;<br />QC": "序列号<br />与质检",
        "Deliver &amp;<br />Invoice": "交付与<br />开票",
        "Complete Firefighting Manufacturing Solutions with Odoo": "完整消防制造 Odoo 方案",
        "Manufacturing Workflow": "制造工作流",
        "Extinguishers": "灭火器",
        "Hose Reels": "消防卷盘",
        "SCBA": "SCBA",
        "Hydrants": "消防栓",
        "Bus Service": "车辆服务",
        "Open Work Orders": "开放工单",
        "Active MOs": "活跃 MO",
        "Serial Units": "序列号单元",
        "QC Pass Rate": "质检通过率",
        "Service Jobs": "服务工单",
        "Operation Mix": "作业构成",
        "Monthly Output &amp; Service Revenue": "月产出与服务收入",
        "Operation Area Mix": "作业区域构成",
        "Centralized": "集中化",
        "Sales, projects, MRP, QC, inventory, service, and finance together.": "销售、项目、MRP、质检、库存、服务与财务一体化。",
        "Automated": "自动化",
        "Turn sales demand into work orders, serials, worksheets, and invoices.": "将销售需求转为工单、序列号、作业单与发票。",
        "Traceable": "可追溯",
        "Track Service IDs, Setsco/TUV serials, barcodes, transfers, and delivery.": "跟踪 Service ID、Setsco/TUV 序列号、条码、调拨与交付。",
        "Controlled": "受控",
        "Support approvals, QC checks, backdate controls, and compliance packs.": "支持审批、质检、倒填日期管控与合规文档包。",
        "Product &amp; BOM Engineering": "产品与 BOM 工程",
        "Extend BOMs with routes, area IDs, SID prefixes, and component-change tools.": "扩展 BOM 含路线、区域 ID、SID 前缀与组件变更工具。",
        "Sales to Work Orders": "销售到工单",
        "Create manufacturing demand and production work orders directly from sales.": "直接从销售创建制造需求与生产工单。",
        "Shop Floor Execution": "车间执行",
        "Track operators, terminals, work sessions, quantities, components, and backorders.": "跟踪操作员、终端、作业会话、数量、组件与欠单。",
        "Serial &amp; Barcode Traceability": "序列号与条码追溯",
        "Manage Service IDs, Setsco serials, QR labels, ranges, scanning, and transfers.": "管理 Service ID、Setsco 序列号、QR 标签、范围、扫描与调拨。",
        "Quality &amp; QC Sheets": "质量与 QC 表格",
        "Reuse QC spreadsheet templates by procurement group and produce QC PDFs.": "按采购组复用 QC 表格模板并生成 QC PDF。",
        "Field Service Worksheets": "现场服务作业单",
        "Handle SCBA, hose reel, hydrant, dry rising, installation, and bus servicing.": "处理 SCBA、卷盘、消防栓、干式立管、安装与车辆维保。",
        "Inventory &amp; Replenishment": "库存与补货",
        "Control stock, no-negative rules, barcode demand, serial ranges, and shortages.": "管控库存、禁负规则、条码需求、序列号范围与缺货。",
        "Documents &amp; Approvals": "文档与审批",
        "Generate certificates, invoices, packing lists, warranties, and tier approvals.": "生成证书、发票、装箱单、保修与分级审批。",
        "Sales": "销售",
        "Demand": "需求",
        "Quotation, order, project, and delivery split": "报价、订单、项目与交付拆分",
        "BOM &amp;": "BOM 与",
        "Planning": "计划",
        "Routes, procurement, deposits, and approvals": "路线、采购、定金与审批",
        "Shop Floor": "车间",
        "Production": "生产",
        "Work sessions, quantities, components, and MOs": "作业会话、数量、组件与 MO",
        "Serial &amp;": "序列号与",
        "QC": "质检",
        "Service IDs, Setsco, barcode labels, QC sheets": "Service ID、Setsco、条码标签与 QC 表",
        "Deliver &amp;": "交付与",
        "Invoice": "开票",
        "Delivery orders, service reports, invoices, certificates": "交付单、服务报告、发票与证书",
        "Serial and distribution control": "序列号与分销管控",
        "Service worksheet tracking": "服务作业单跟踪",
        "Testing and service products": "检测与服务产品",
        "Testing and field records": "检测与现场记录",
        "Labour and component usage": "人工与组件耗用",
        "Tier Validation": "分级校验",
        "Milestone Billing": "里程碑开票",
        "Invoice From Delivery": "按交付开票",
        "SG Payment File": "新加坡付款文件",
        "Mobile Barcode Scan": "移动条码扫描",
        "XLSX Service Reports": "XLSX 服务报告",
        "Min/Max Shortage Alerts": "最小/最大缺货预警",
        "Compliance Print Pack": "合规打印包",
        "1.8k": "1.8k",
        "Manufacturing 58%": "制造 58%",
        "Field Service 24%": "现场服务 24%",
        "Projects 18%": "项目 18%",
        "Fire Extinguisher": "灭火器",
        "SCBA Testing": "SCBA 检测",
        "QC Inspection": "QC 检验",
        "Project Billing": "项目开票",
        "PDF/XLSX": "PDF/XLSX",
        "MO-1842": "MO-1842",
        "Site A": "现场 A",
        "SO-1847": "SO-1847",
        "Client B": "客户 B",
        "QC-1851": "QC-1851",
        "PRJ-1854": "PRJ-1854",
        "Contract C": "合同 C",
        "Better Sales to Production Flow": "更优销售到生产流程",
        "Connect quotations, demand planning, work orders, procurement, and delivery.": "贯通报价、需求计划、工单、采购与交付。",
        "Full Serial Traceability": "完整序列号追溯",
        "Track manufactured units, Setsco/TUV references, barcodes, transfers, and service history.": "跟踪制造单元、Setsco/TUV 参考、条码、调拨与服务历史。",
        "Quality &amp; Compliance Control": "质量与合规管控",
        "Standardize QC, certificates, warranties, approvals, and audit-ready documents.": "标准化 QC、证书、保修、审批与审计就绪文档。",
        "Service Team Efficiency": "服务团队效率",
        "Turn field worksheets into service products, delivery demand, reports, and invoices.": "将现场作业单转为服务产品、交付需求、报告与发票。",
    },
    "secondary-process-manufacturing": {
        "Alitec's manufacturing solution helps secondary-process factories receive customer materials, run traveler-based production jobs, control IQC and OQC quality gates, merge and split shop orders, and track every job from intake to release in one Odoo platform.":
            "Alitec 制造方案帮助二次加工工厂接收客供料、运行流转单生产作业、管控 IQC 与 OQC 质量关卡、合并拆分车间订单，并在 Odoo 平台跟踪从入厂到放行的每一票作业。",
        "Alitec's manufacturing solution helps secondary-process factories receive customer\n        materials, run traveler-based production jobs, control IQC and OQC quality gates,\n        merge and split shop orders, and track every job from intake to release in one Odoo platform.":
            "Alitec 制造方案帮助二次加工工厂接收客供料、运行流转单生产作业、管控 IQC 与 OQC 质量关卡、合并拆分车间订单，并在 Odoo 平台跟踪从入厂到放行的每一票作业。",
        "Secondary Process<br />Manufacturing": "二次加工<br />制造",
        "Secondary Process": "二次加工",
        "Receive<br />Material": "接收<br />物料",
        "Create<br />Job": "创建<br />作业",
        "Run<br />Operations": "运行<br />工序",
        "IQC / OQC<br />Checks": "IQC / OQC<br />检验",
        "Release &amp;<br />Return": "放行与<br />退回",
        "Incoming Jobs, IQC/OQC &amp; Shop Floor Control with Odoo": "来料加工、IQC/OQC 与车间管控",
        "Production Workflow": "生产工作流",
        "IQC / OQC": "IQC / OQC",
        "Traveler Route": "流转单路线",
        "Combine Batch": "合并批次",
        "Engineering": "工程",
        "IORA Flag": "IORA 标记",
        "IQC Pending": "IQC 待检",
        "OQC Queue": "OQC 队列",
        "Combined Jobs": "合并作业",
        "Phase Mix": "阶段构成",
        "Weekly Job Volume": "周作业量",
        "Jobs by Phase Status": "按阶段状态作业",
        "Upcoming Releases": "即将放行",
        "Traveler Routing": "流转单路线",
        "Customer parts drive production through traveler templates and phased routings.": "客户零件经流转单模板与分阶段路线驱动生产。",
        "IQC / OQC Gates": "IQC / OQC 关卡",
        "Incoming and outgoing quality phases with reject, rework, and engineering holds.": "来料与出货质量阶段，含拒收、返工与工程冻结。",
        "Merge Shop Orders": "合并车间订单",
        "Combine manufacturing orders at the next shared ready shop-floor operation.": "在下一相同就绪车间工序合并制造订单。",
        "Full Job Tracking": "完整作业跟踪",
        "Split, combine, serial, and lineage tracking across every production job.": "拆批、合并、序列号与谱系跟踪贯穿每票生产作业。",
        "Traveler Templates": "流转单模板",
        "Link customer parts to internal BoM and routing templates.": "将客户零件关联内部 BoM 与路线模板。",
        "Incoming Material": "来料",
        "Register received parts and launch jobs from material intake.": "登记收料零件并从入厂启动作业。",
        "IQC &amp; OQC Phases": "IQC 与 OQC 阶段",
        "Tag work centers for incoming and outgoing quality checkpoints.": "为来料与出货质检点标记工作中心。",
        "Split Production Lots": "拆分生产批次",
        "Split quantities while preserving work order and check history.": "拆分数量同时保留工单与检验历史。",
        "Batch orders at the same ready shop-floor operation.": "在相同就绪车间工序批量合并订单。",
        "Rework &amp; Reject": "返工与拒收",
        "Route rejected qty to repair, engineering, and quality stations.": "将拒收数量路由至维修、工程与质量工位。",
        "Serial &amp; Lineage": "序列号与谱系",
        "Register serials and trace split, combine, and origin MO links.": "登记序列号并追溯拆分、合并与源 MO 关联。",
        "Compliance Docs": "合规文档",
        "Specs, quality records, and barcoded travelers for customer release.": "规格、质量记录与条码流转单供客户放行。",
        "Receive": "接收",
        "Material": "物料",
        "Log incoming customer parts with specs and traveler mapping": "记录来料客户零件含规格与流转单映射",
        "Create": "创建",
        "Job": "作业",
        "Launch MO from customer product to traveler template routing": "从客户产品按流转单模板路线启动 MO",
        "Run": "运行",
        "Operations": "工序",
        "Execute process stations on the shop floor with work orders": "用工单在车间执行工艺工位",
        "Checks": "检验",
        "Complete quality checks; reject or rework nonconforming qty": "完成质量检验；拒收或返工不合格数量",
        "Release &amp;": "放行与",
        "Return": "退回",
        "Finish jobs, document quality results, and return to customer": "完成作业、记录质量结果并退回客户",
        "Phase-tagged work centers for quality gates": "质量关卡阶段标记工作中心",
        "Customer part maps to internal routing template": "客户零件映射内部路线模板",
        "Merge MOs at the same ready operation": "在相同就绪工序合并 MO",
        "Hold and repair routing for rejected jobs": "拒收作业冻结与返修路线",
        "Customer agreement path on IQC rejection": "IQC 拒收客户确认路径",
        "Shop-floor split production lots": "车间拆分生产批次",
        "Rework inserted before OQC": "OQC 前插入返工",
        "Serial registration on MO": "MO 序列号登记",
        "Barcoded traveler printouts": "条码流转单打印",
        "Specs and drawings on products": "产品规格与图纸",
        "Split and combine MO lineage": "拆分与合并 MO 谱系",
        "Material, treatment, and RoHS data": "材料、处理与 RoHS 数据",
        "Quality records for release docs": "放行文档质量记录",
        "Process (156) 58%": "加工 (156) 58%",
        "QC Gates (112) 42%": "质检关卡 (112) 42%",
        "IQC Gate": "IQC 关卡",
        "Combined MOs": "合并 MO",
        "OQC Release": "OQC 放行",
        "Eng": "工程",
        "Hold": "冻结",
        "In Process": "加工中",
        "IQC Hold": "IQC 冻结",
        "OQC Ready": "OQC 就绪",
        "Rework": "返工",
        "Customer Part": "客户零件",
        "Phase": "阶段",
        "MO-1182": "MO-1182",
        "Housing Assy": "壳体组件",
        "Fri 14:00": "周五 14:00",
        "OQC": "OQC",
        "MO-1186": "MO-1186",
        "Shaft Blank": "轴坯",
        "Fri 16:30": "周五 16:30",
        "IQC": "IQC",
        "MO-1191": "MO-1191",
        "Bracket Set": "支架组",
        "Mon 09:00": "周一 09:00",
        "MO-1194": "MO-1194",
        "Cover Plate": "盖板",
        "Mon 11:00": "周一 11:00",
        "Controlled Intake": "受控入厂",
        "Turn incoming customer material into structured production jobs.": "将来料客户物料转为结构化生产作业。",
        "Quality at Every Gate": "每道关卡质量",
        "IQC and OQC phases with clear reject and rework paths.": "IQC 与 OQC 阶段含清晰拒收与返工路径。",
        "Smarter Batching": "更智能合批",
        "Merge orders only when they share the same next operation.": "仅在共享下一工序时合并订单。",
        "Traceable Release": "可追溯放行",
        "Track splits, combines, and documentation for customer conformance.": "跟踪拆分、合并与文档以满足客户符合性。",
    },
    "food-manufacturing-operations": {
        "Alitec's food manufacturing solution helps fresh-food producers plan daily outlet production, generate manufacturing and delivery orders together, enforce outlet-level cost control, and reconcile commission sales in one Odoo platform.":
            "Alitec 食品制造方案帮助鲜食生产商计划每日门店生产、同步生成制造与交付订单、强制门店级成本管控，并在 Odoo 平台对账代销销售。",
        "Alitec's food manufacturing solution helps fresh-food producers plan daily\n        outlet production, generate manufacturing and delivery orders together,\n        enforce outlet-level cost control, and reconcile commission sales in one Odoo platform.":
            "Alitec 食品制造方案帮助鲜食生产商计划每日门店生产、同步生成制造与交付订单、强制门店级成本管控，并在 Odoo 平台对账代销销售。",
        "Food Manufacturing<br />Operations": "食品制造<br />运营",
        "Food Manufacturing": "食品制造",
        "Operations": "运营",
        "Fresh Food &amp; Sushi Production — From Kitchen to Outlet with Odoo": "鲜食与寿司生产 — 从厨房到门店",
        "Configure<br />Outlets": "配置<br />门店",
        "Run<br />Produce": "运行<br />生产",
        "Manufacture<br />&amp; Deliver": "制造与<br />交付",
        "Sell &amp;<br />Procure": "销售与<br />采购",
        "Reconcile<br />&amp; Bill": "对账与<br />开票",
        "Outlet Analytics": "门店分析",
        "Day Planning": "日计划",
        "Finance Approval": "财务审批",
        "Scrap Approval": "报废审批",
        "Credit Limits": "信用额度",
        "MOs Due Today": "今日到期 MO",
        "Components Ready": "组件就绪",
        "Open Deliveries": "开放交付",
        "Scrap Pending": "待报废",
        "Commission Imports": "代销导入",
        "Production by Outlet": "按门店生产",
        "Weekly Production Volume": "周生产量",
        "Production Mix": "生产构成",
        "Produce to Outlet": "生产至门店",
        "Production templates generate manufacturing orders and delivery orders together for each outlet.": "生产模板为各门店同步生成制造订单与交付订单。",
        "Margin by Outlet": "按门店毛利",
        "Analytic accounts are required across sales, purchases, production, and invoicing.": "销售、采购、生产与开票均强制分析账户。",
        "Commission Billing": "代销开票",
        "Excel sales imports create customer invoices and matching commission credit notes.": "Excel 销售导入生成客户发票与匹配代销贷项通知单。",
        "Expiry Traceability": "效期追溯",
        "Delivery slips and invoices print lot, serial, and expiration dates for perishable goods.": "交付单与发票打印批次、序列号与效期。",
        "Outlet Production Templates": "门店生产模板",
        "Plan daily production by outlet, location, analytic account, and product quantity.": "按门店、库位、分析账户与产品数量计划日生产。",
        "MO + Delivery Generation": "MO 与交付生成",
        "Create manufacturing orders and outlet deliveries from one wizard action.": "一个向导动作同时创建制造订单与门店交付。",
        "Analytic Control": "分析管控",
        "Enforce outlet cost centers on sales, purchases, MOs, invoices, and inventory moves.": "在销售、采购、MO、发票与库存移动强制门店成本中心。",
        "Excel Sales Import": "Excel 销售导入",
        "Map third-party sales lines to products and outlets from spreadsheet uploads.": "从电子表格映射第三方销售行至产品与门店。",
        "Commission Automation": "代销自动化",
        "Generate customer invoices and commission credit notes from imported sales.": "从导入销售生成客户发票与代销贷项通知单。",
        "Split Deliveries": "拆分交付",
        "Support per-line delivery addresses and separate pickings by destination.": "支持按行交付地址与按目的地拆分拣货。",
        "Lot &amp; Expiry Docs": "批次与效期文档",
        "Show manufacturing and expiration detail on delivery slips and invoices.": "交付单与发票显示生产与效期明细。",
        "Branded PDF Output": "品牌 PDF 输出",
        "Print sales, purchase, delivery, invoice, receipt, and statement layouts.": "打印销售、采购、交付、发票、收据与对账单版式。",
        "Configure": "配置",
        "Outlets": "门店",
        "Set products, analytic accounts, and production templates": "设置产品、分析账户与生产模板",
        "Produce": "生产",
        "Launch daily production for the scheduled outlet plan": "按排程门店计划启动日生产",
        "Manufacture": "制造",
        "&amp; Deliver": "与交付",
        "Complete MOs and ship finished goods to outlets": "完成 MO 并将成品发至门店",
        "Sell &amp;": "销售与",
        "Procure": "采购",
        "Process sales and purchases with mandatory analytics": "处理强制分析账户的销售与采购",
        "Reconcile": "对账",
        "&amp; Bill": "与开票",
        "Import commission sales, post invoices, and print documents": "导入代销销售、过账发票并打印文档",
        "Cost centers enforced across operations": "运营全程强制成本中心",
        "Schedule production templates by day": "按日排程生产模板",
        "Control customer and partner activation": "管控客户与合作伙伴激活",
        "Gate scrap validation before posting": "过账前门禁报废校验",
        "Partner credit governance on transactions": "交易合作伙伴信用治理",
        "Auto product SKU by category": "按类别自动生成 SKU",
        "Mandatory sales delivery dates": "强制销售交付日期",
        "Per-line delivery addresses": "按行交付地址",
        "Lot manufacturing date tracking": "批次生产日期跟踪",
        "Manned location visibility on MOs": "MO 显示有人值守库位",
        "B2B website cart with UoM display": "B2B 网站购物车显示计量单位",
        "Inventory adjustment analytics": "库存调整分析",
        "Custom aged balance reporting": "定制账龄余额报表",
        "Central Kitchen (148) 62%": "中央厨房 (148) 62%",
        "Outlet Dispatch (91) 38%": "门店配送 (91) 38%",
        "Outlet MOs": "门店 MO",
        "Supervisors": "主管",
        "SKU-101": "SKU-101",
        "SKU-204": "SKU-204",
        "SKU-318": "SKU-318",
        "SKU-422": "SKU-422",
        "Connected Production Flow": "贯通生产流程",
        "Link planning, manufacturing, delivery, sales, and billing on one platform.": "计划、制造、交付、销售与开票统一于平台。",
        "Outlet-Level Control": "门店级管控",
        "See cost, revenue, and fulfillment performance by outlet.": "按门店查看成本、收入与履约绩效。",
        "Faster Commission Processing": "更快代销处理",
        "Turn spreadsheet sales into invoice and credit note pairs automatically.": "自动将电子表格销售转为发票与贷项通知单对。",
        "Fresh-Food Traceability": "鲜食追溯",
        "Carry lot and expiry detail through documents customers and auditors expect.": "在客户与审计所需文档中贯穿批次与效期。",
    },
    "attendance-timesheet-hardware": {
        "Alitec's attendance and timesheet solution on Odoo helps operations teams connect biometric punch data, employee attendance control, and team-based timesheet work in one managed workflow. It brings device sync, daily in/out processing, and export-ready timesheet control into one cleaner operation flow.":
            "Alitec 考勤与工时表 Odoo 方案帮助运营团队将生物识别打卡数据、员工考勤管控与团队工时表工作纳入统一流程，实现设备同步、每日进出处理与可导出工时表管控。",
        "Attendance &amp; Hardware Integration": "考勤与硬件集成",
        "Connect<br />Device": "连接<br />设备",
        "Sync<br />Logs": "同步<br />日志",
        "Match<br />Employee": "匹配<br />员工",
        "Process<br />Daily In/Out": "处理<br />每日进出",
        "Export<br />Attendance": "导出<br />考勤",
        "Review<br />Timesheets": "审核<br />工时表",
        "Biometric capture, daily in/out processing, Excel payroll exports, and site-ready timesheet control":
            "生物识别采集、每日进出处理、Excel 薪资导出与现场就绪工时表管控",
        "Attendance Workflow": "考勤工作流",
        "Late Minutes": "迟到分钟",
        "No Check Out": "未签退",
        "Team History": "团队历史",
        "Day / Night Split": "白班/夜班拆分",
        "Background Jobs": "后台任务",
        "Connected Devices": "已连接设备",
        "Daily Punches": "每日打卡",
        "No Checkout": "未签退",
        "Night Shift": "夜班",
        "Imported Sheets": "已导入工时表",
        "Attendance Status Mix": "考勤状态构成",
        "Monthly Processed Attendance": "月度已处理考勤",
        "Direct device sync": "直连设备同步",
        "Bring biometric logs into Odoo with device, area, and connection visibility.": "将生物识别日志导入 Odoo，含设备、区域与连接状态可视化。",
        "Daily attendance control": "每日考勤管控",
        "Build one simple table with in/out time, status, and device traceability.": "构建含进出时间、状态与设备追溯的简洁表格。",
        "Shift-aware processing": "班次感知处理",
        "Split day and night hours, preserve manual overrides, and review missing punches.": "拆分白班夜班工时，保留手工覆盖并审核缺卡。",
        "Timesheet-ready operations": "工时表就绪运营",
        "Import worker sheets from Excel or CSV and move them through approval.": "从 Excel 或 CSV 导入工时表并走审批流程。",
        "ZKTeco device registry": "ZKTeco 设备注册",
        "Track devices, area, timezone, connection state, last signal, user count, and attendance count inside Odoo.": "在 Odoo 内跟踪设备、区域、时区、连接状态、最后信号、用户数与考勤数。",
        "Employee code mapping": "员工编码映射",
        "Match device PIN or code combinations back to Odoo employees for reliable log ownership.": "将设备 PIN 或编码组合映射回 Odoo 员工，确保日志归属准确。",
        "Attendance log capture": "考勤日志采集",
        "Download or sync raw punch logs, keep device references, and prepare the records for attendance processing.": "下载或同步原始打卡日志，保留设备参考并准备考勤处理。",
        "Smart and punch processing": "智能与打卡处理",
        "Convert logs into attendance using either shift-aware smart logic or punch-state rules with tolerance handling.": "用班次感知智能逻辑或打卡状态规则（含容差）将日志转为考勤。",
        "Simple attendance table": "简洁考勤表",
        "Store one daily record per employee with device in and out details, worked hours, and completion status.": "每员工每日一条记录，含设备进出明细、工时与完成状态。",
        "Shift and team control": "班次与团队管控",
        "Split day and night hours, preserve manual overrides, and apply current or dated team history in output.": "拆分白班夜班，保留手工覆盖，输出应用当前或历史团队。",
        "Excel export pack": "Excel 导出包",
        "Generate staff and worker attendance sheets with check-in, device name, NT, OT, and period-ready layouts.": "生成员工考勤表，含签到、设备名、NT、OT 与期间版式。",
        "Bulk timesheet import": "批量工时表导入",
        "Import site timesheets from Excel or CSV, auto-create workers, teams, and positions, then confirm and approve.": "从 Excel/CSV 导入现场工时表，自动创建工人、团队与岗位后确认审批。",
        "Connect": "连接",
        "Device": "设备",
        "Sync": "同步",
        "Logs": "日志",
        "Match": "匹配",
        "Employee": "员工",
        "Process": "处理",
        "Daily In/Out": "每日进出",
        "Export": "导出",
        "Attendance": "考勤",
        "Review": "审核",
        "Timesheets": "工时表",
        "One operating flow for biometric capture, attendance cleanup, shift handling, export, and team-based timesheet review.":
            "生物识别采集、考勤整理、班次处理、导出与团队工时表审核一体化流程。",
        "Download device users": "下载设备用户",
        "Global recalculate": "全局重算",
        "Manual override notes": "手工覆盖备注",
        "Area and timezone setup": "区域与时区设置",
        "Auto-create workers": "自动创建工人",
        "Approve imported sheets": "审批导入工时表",
        "2.4k": "2.4k",
        "Complete 61%": "完成 61%",
        "Pending review 18%": "待审核 18%",
        "Imported timesheets 21%": "已导入工时表 21%",
        "Biometric Logs": "生物识别日志",
        "Devices": "设备",
        "Simple Attendance": "简洁考勤",
        "Processing": "处理中",
        "Worker Export": "工人导出",
        "Excel": "Excel",
        "Imported Timesheets": "已导入工时表",
        "XLS / CSV": "XLS / CSV",
        "Faster Attendance Consolidation": "更快考勤汇总",
        "Reduce manual copying from devices and keep employee punch activity in one Odoo-controlled flow.": "减少从设备手工复制，将员工打卡活动纳入 Odoo 管控流程。",
        "Payroll-Ready Export Output": "薪资就绪导出",
        "Prepare structured attendance sheets with check times, devices, and working-hour breakdowns.": "准备结构化考勤表，含打卡时间、设备与工时拆分。",
        "Better Shift and Exception Control": "更优班次与异常管控",
        "Track late minutes, no-checkout cases, manual overrides, and recalculation across date ranges.": "跟踪迟到、未签退、手工覆盖与跨日期重算。",
        "Stronger Team and Site Visibility": "更强团队与现场可视化",
        "Import site timesheets, apply team structure, and move records through review and approval.": "导入现场工时表，应用团队结构并走审核审批。",
    },
    "translation-service-operations": {
        "Alitec's translation solution helps language service providers manage client quotes, translation projects, vendor assignments, and billing — with third-party translation tool integration, document-level vendor POs, and language-pair product catalogs in one Odoo platform.":
            "Alitec 翻译方案帮助语言服务商管理客户报价、翻译项目、供应商分配与开票 — 含第三方翻译工具集成、文档级供应商 PO 与语言对产品目录，统一于 Odoo 平台。",
        "Alitec's translation solution helps language service providers manage client quotes,\n        translation projects, vendor assignments, and billing — with third-party translation\n        tool integration, document-level vendor POs, and language-pair product catalogs in one Odoo platform.":
            "Alitec 翻译方案帮助语言服务商管理客户报价、翻译项目、供应商分配与开票 — 含第三方翻译工具集成、文档级供应商 PO 与语言对产品目录，统一于 Odoo 平台。",
        "Translation Service<br />Operations": "翻译服务<br />运营",
        "Translation Service": "翻译服务",
        "Quote<br />Client": "向客户<br />报价",
        "Confirm &amp;<br />Kickoff": "确认并<br />启动",
        "Assign<br />Vendors": "分配<br />供应商",
        "Create<br />Vendor POs": "创建<br />供应商 PO",
        "Invoice<br />Client": "向客户<br />开票",
        "Language Projects — From Quote to Delivery with Odoo": "语言项目 — 从报价到交付",
        "Language Pairs": "语言对",
        "Word / Char": "字数/字符",
        "Tool Sync": "工具同步",
        "Active Projects": "活跃项目",
        "Docs In Progress": "进行中文档",
        "Live CAT Jobs": "运行中 CAT 作业",
        "Open Vendor POs": "开放供应商 PO",
        "Service Mix": "服务构成",
        "Weekly Project Volume": "周项目量",
        "Top Language Pairs": "热门语言对",
        "Upcoming Deadlines": "即将到期",
        "Third-Party Tools": "第三方工具",
        "Connect your CAT or translation platform and sync document status and assignments.": "连接 CAT 或翻译平台，同步文档状态与分配。",
        "Vendor PO Auto": "供应商 PO 自动",
        "Create purchase orders from documents with word, character, or min-charge pricing.": "按字数、字符数或最低收费从文档创建采购订单。",
        "Project Control": "项目管控",
        "Deadlines, PMs, turnaround times, and delivery formats on every job.": "每票作业含截止日期、PM、周转时间与交付格式。",
        "Language Catalog": "语言目录",
        "Products mapped by source language, target language, and TR/TEP/REV type.": "产品按源语言、目标语言与 TR/TEP/REV 类型映射。",
        "Quotation Templates": "报价模板",
        "Pre-fill memo notes, turnaround time, and delivery format on new quotes.": "新报价预填备注、周转时间与交付格式。",
        "Sale to Project": "销售转项目",
        "Auto-create projects with deadlines, PM, and analytic accounts from orders.": "从订单自动创建含截止日期、PM 与分析账户的项目。",
        "CAT Tool Integration": "CAT 工具集成",
        "Connect third-party translation tools and pull document assignments and weighted counts.": "连接第三方翻译工具，拉取文档分配与加权计数。",
        "Translation Documents": "翻译文档",
        "Track translators, reviewers, status, and weighted words or characters.": "跟踪译员、审校、状态与加权字数/字符。",
        "Vendor Purchase Orders": "供应商采购订单",
        "Generate POs from document assignments using supplier pricelists.": "按供应商价目表从文档分配生成 PO。",
        "Language-Pair Products": "语言对产品",
        "Catalog products by source, target, and translation service type.": "按源语言、目标语言与翻译服务类型编目产品。",
        "Project File Folders": "项目文件夹",
        "Auto-copy folder structure when a new translation project starts.": "新翻译项目启动时自动复制文件夹结构。",
        "Job Order Reports": "作业单报告",
        "Print quotations, invoices, and job orders with custom layouts.": "以定制版式打印报价、发票与作业单。",
        "Quote": "报价",
        "Client": "客户",
        "Build quotation with language lines, deadline, and project details": "构建含语言行、截止日期与项目明细的报价",
        "Confirm &amp;": "确认并",
        "Kickoff": "启动",
        "Convert to project, launch the CAT job, and copy project folders": "转为项目、启动 CAT 作业并复制项目文件夹",
        "Assign": "分配",
        "Vendors": "供应商",
        "Sync translators and reviewers from translation tool assignments": "从翻译工具分配同步译员与审校",
        "Vendor POs": "供应商 PO",
        "Generate POs from weighted word or character counts": "按加权字数或字符数生成 PO",
        "Bill completed work with branded quotation and invoice docs": "以品牌报价与发票文档对已完成工作开票",
        "Source and destination validation on every order": "每单校验源语言与目标语言",
        "TR, TEP, and REV routing for vendor products": "供应商产品 TR、TEP、REV 路由",
        "Unit pricing with minimum charge fallback rules": "单价含最低收费回退规则",
        "Per-project analytic account tracking": "按项目分析账户跟踪",
        "Scheduled status and document updates from CAT tools": "CAT 工具定时状态与文档更新",
        "Bulk contact and quotation import": "批量联系人与报价导入",
        "Custom job order and invoice layouts": "定制作业单与发票版式",
        "Auto project folder duplication": "自动复制项目文件夹",
        "PM alert when CAT project is ready": "CAT 项目就绪时 PM 提醒",
        "Sales team data security": "销售团队数据安全",
        "Delivery order reports from sales": "从销售生成交付单报告",
        "Turnaround and delivery format fields": "周转与交付格式字段",
        "Vendor contacts mapped to translation tool users": "供应商联系人映射翻译工具用户",
        "Translation (186) 58%": "翻译 (186) 58%",
        "TEP / Review (134) 42%": "TEP / 审校 (134) 42%",
        "PM Team": "PM 团队",
        "Deadlines": "截止日期",
        "EN→JA": "英→日",
        "EN→ZH": "英→中",
        "JA→EN": "日→英",
        "EN→KO": "英→韩",
        "PRJ-2041": "PRJ-2041",
        "Tech Manual": "技术手册",
        "Fri 17:00": "周五 17:00",
        "TR": "TR",
        "PRJ-2045": "PRJ-2045",
        "Legal Contract": "法律合同",
        "Sat 12:00": "周六 12:00",
        "TEP": "TEP",
        "PRJ-2048": "PRJ-2048",
        "Marketing Site": "营销网站",
        "PRJ-2052": "PRJ-2052",
        "Annual Report": "年报",
        "Mon 15:00": "周一 15:00",
        "REV": "REV",
        "Faster Kickoff": "更快启动",
        "Move from confirmed quote to CAT project and folders in one flow.": "从确认报价到 CAT 项目与文件夹一步完成。",
        "Accurate Vendor Billing": "精准供应商开票",
        "PO lines based on real document word counts and vendor rates.": "PO 行基于真实文档字数与供应商费率。",
        "Deadlines, assignments, and CAT tool status in one dashboard.": "截止日期、分配与 CAT 工具状态一屏掌握。",
        "Consistent Documents": "一致文档",
        "Branded quotations, job orders, and invoices every time.": "每次输出品牌报价、作业单与发票。",
    },
    "gym-equipment-sales-service": {
        "Alitec's gym equipment solution helps distributors sell through B2B and online channels, register installed machines on delivery, run maintenance contracts, and complete signed field service visits — all in one Odoo platform.":
            "Alitec 健身器材方案帮助分销商通过 B2B 与在线渠道销售、在交付时登记安装设备、运行维保合同并完成签字现场服务 — 统一于 Odoo 平台。",
        "Alitec's gym equipment solution helps distributors sell through B2B and online channels,\n        register installed machines on delivery, run maintenance contracts, and complete signed\n        field service visits — all in one Odoo platform.":
            "Alitec 健身器材方案帮助分销商通过 B2B 与在线渠道销售、在交付时登记安装设备、运行维保合同并完成签字现场服务 — 统一于 Odoo 平台。",
        "Gym Equipment<br />Sales &amp; Service": "健身器材<br />销售与服务",
        "Gym Equipment": "健身器材",
        "Sales &amp; Service": "销售与服务",
        "B2B &amp; B2C Distribution — Sales, Delivery &amp; Maintenance with Odoo": "B2B 与 B2C 分销 — 销售、交付与维保",
        "Service Workflow": "服务工作流",
        "Quote<br />&amp; Sell": "报价<br />与销售",
        "Deliver &amp;<br />Register": "交付与<br />登记",
        "Open<br />Contract": "开通<br />合同",
        "Schedule<br />Service": "排程<br />服务",
        "Complete<br />&amp; Bill": "完成与<br />开票",
        "Sales Teams": "销售团队",
        "Billing Types": "账单类型",
        "Service Types": "服务类型",
        "Warranty": "保修",
        "Appointments": "预约",
        "Open Service Orders": "开放服务订单",
        "Contracts Due": "合同到期",
        "Equipment On Site": "现场设备",
        "Renewals Due": "续费到期",
        "Service Mix": "服务构成",
        "Weekly Service Volume": "周服务量",
        "Sales Channel Mix": "销售渠道构成",
        "Upcoming Service Visits": "即将服务拜访",
        "Dual Sales Channels": "双销售渠道",
        "Run B2B quotes and B2C web orders from one equipment catalog.": "从统一设备目录运行 B2B 报价与 B2C 网站订单。",
        "Installed Equipment": "已安装设备",
        "Track every machine by customer, serial number, and site location.": "按客户、序列号与现场位置跟踪每台设备。",
        "Contract Maintenance": "合同维保",
        "Schedule recurring visits and batch monthly service orders.": "排程定期拜访并批量生成月度服务订单。",
        "Field Service Docs": "现场服务文档",
        "Checklists, parts used, and signed maintenance or repair reports.": "检查清单、使用零件与签字维保/维修报告。",
        "Brand &amp; Category Catalog": "品牌与品类目录",
        "Subcategories, brands, dimensions, and footprints on equipment products.": "设备产品含子类、品牌、尺寸与占地面积。",
        "B2B Sales Tools": "B2B 销售工具",
        "Target discounts, delivery contacts, and after-sales quotation types.": "目标折扣、交付联系人与售后报价类型。",
        "eCommerce Storefront": "eCommerce 店面",
        "Online fitness shop with brands, filters, and checkout options.": "在线健身商城含品牌、筛选与结账选项。",
        "Equipment Registration": "设备登记",
        "Register serial-numbered assets when equipment is delivered on site.": "现场交付时登记序列号资产。",
        "Maintenance Contracts": "维保合同",
        "Lump sum, per-service, leasing, and renewal quotation flows.": "包干、按次、租赁与续费报价流程。",
        "Service Orders": "服务订单",
        "Maintenance, repair, troubleshooting, commissioning, and shifting.": "维保、维修、故障排查、调试与搬迁。",
        "Service Checklists": "服务检查清单",
        "Product-linked templates completed on every service visit.": "每次服务拜访完成产品关联模板。",
        "Signed Service Reports": "签字服务报告",
        "Digital signatures on delivery and service PDF documents.": "交付与服务 PDF 数字签名。",
        "&amp; Sell": "与销售",
        "B2B quotation or web order with brand catalog and warranties": "B2B 报价或含品牌目录与保修的网站订单",
        "Register": "登记",
        "Signed delivery, serial capture, push equipment to after-sales": "签字交付、序列号采集并推送至售后",
        "Open": "开通",
        "Contract": "合同",
        "Link machines to maintenance contract with billing and frequency": "将设备关联维保合同含账单与频率",
        "Schedule": "排程",
        "Service": "服务",
        "Generate monthly maintenance or on-demand repair orders": "生成月度维保或按需维修订单",
        "Complete": "完成",
        "&amp; Bill": "与开票",
        "Checklists, signatures, service PDFs, and follow-up invoices": "检查清单、签名、服务 PDF 与跟进发票",
        "Standard vs after-sales team routing on quotations": "报价标准团队与售后团队路由",
        "Lump sum, per service, leasing, and free service contracts": "包干、按次、租赁与免费服务合同",
        "Maintenance, repair, troubleshooting, and commissioning": "维保、维修、故障排查与调试",
        "Warranty codes and extensions on installed equipment": "已安装设备保修码与延期",
        "Time-in/time-out and scheduled visit windows on orders": "订单含进出时间与预约拜访窗口",
        "Branded sales and delivery print layouts": "品牌销售与交付打印版式",
        "Monthly maintenance batch wizard": "月度维保批量向导",
        "Parts replacement list on service orders": "服务订单零件更换清单",
        "Subscription billing UI support": "订阅账单 UI 支持",
        "Consignment picking linked to sales": "寄售拣货关联销售",
        "Email service PDFs to customers": "邮件发送服务 PDF 给客户",
        "CRM and inventory dashboards": "CRM 与库存仪表盘",
        "Target discount on B2B quotations": "B2B 报价目标折扣",
        "Maintenance (142) 61%": "维保 (142) 61%",
        "Repair / Other (91) 39%": "维修/其他 (91) 39%",
        "Repairs": "维修",
        "Field Ops": "现场运营",
        "Deliveries": "交付",
        "Renewals": "续费",
        "B2B": "B2B",
        "B2C Web": "B2C 网站",
        "After-Sales": "售后",
        "Contracts": "合同",
        "SO-1842": "SO-1842",
        "FitZone Gym": "FitZone 健身房",
        "Fri 10:00": "周五 10:00",
        "SO-1847": "SO-1847",
        "City Sports Club": "城市体育俱乐部",
        "Sat 09:30": "周六 09:30",
        "SO-1851": "SO-1851",
        "Hotel Wellness": "酒店康体",
        "Mon 14:00": "周一 14:00",
        "SO-1854": "SO-1854",
        "Retail Buyer": "零售买家",
        "Tue 11:00": "周二 11:00",
        "One Equipment Record": "统一设备档案",
        "From sale and delivery through every service visit.": "从销售交付到每次服务拜访。",
        "Predictable Maintenance": "可预期维保",
        "Contracts drive next visit dates and monthly scheduling.": "合同驱动下次拜访日期与月度排程。",
        "Professional Field Reports": "专业现场报告",
        "Signed checklists and PDFs for every job.": "每票作业签字检查清单与 PDF。",
        "Channel Flexibility": "渠道灵活性",
        "Serve gyms, dealers, and retail buyers in one system.": "在同一系统服务健身房、经销商与零售买家。",
    },
    "specialty-chemical-trading": {
        "Alitec's chemical trading solution helps distributors manage indent and ex-stock sales, margin-controlled quotations, batch traceability, landed import costs, and multi-level approvals — across sales, warehouse, and finance in one Odoo platform.":
            "Alitec 化学品贸易方案帮助分销商管理订货与现货销售、毛利管控报价、批次追溯、进口到岸成本与多级审批 — 销售、仓库与财务统一于 Odoo 平台。",
        "Alitec's chemical trading solution helps distributors manage indent and ex-stock sales,\n        margin-controlled quotations, batch traceability, landed import costs, and multi-level\n        approvals — across sales, warehouse, and finance in one Odoo platform.":
            "Alitec 化学品贸易方案帮助分销商管理订货与现货销售、毛利管控报价、批次追溯、进口到岸成本与多级审批 — 销售、仓库与财务统一于 Odoo 平台。",
        "Specialty Chemical<br />Trading": "特种化学品<br />贸易",
        "Specialty Chemical": "特种化学品",
        "Trading": "贸易",
        "Regional Distribution — Sales, Import &amp; Compliance with Odoo": "区域分销 — 销售、进口与合规",
        "Trading Workflow": "贸易工作流",
        "Quote &amp;<br />Approve": "报价与<br />审批",
        "Order &amp;<br />Source": "下单与<br />寻源",
        "Receive &amp;<br />Cost": "收货与<br />成本",
        "Deliver &amp;<br />Invoice": "交付与<br />开票",
        "Monitor &amp;<br />Report": "监控与<br />报表",
        "Indent / Ex-Stock": "订货 / 现货",
        "Trade Types": "贸易类型",
        "Customer Grade": "客户等级",
        "Slow Moving Stock": "滞销库存",
        "Under Approval": "审批中",
        "Open Indents": "开放订货",
        "Shelf-Life Alerts": "保质期预警",
        "Below VOC": "低于 VOC",
        "AR Due 30d": "30 天应收",
        "Order Mix": "订单构成",
        "Weekly Quotation Volume": "周报价量",
        "Business Unit Volume": "业务单元量",
        "Quotations Awaiting Approval": "待审批报价",
        "Trade Order Control": "贸易订单管控",
        "Indent and ex-stock flows with ports, incoterms, and shipment terms.": "订货与现货流程含港口、贸易术语与装运条款。",
        "Margin Governance": "毛利治理",
        "VOC and minimum price checks before quotations are released.": "报价发布前 VOC 与最低售价检查。",
        "Batch Traceability": "批次追溯",
        "Lots, shelf life, and expiration on receipts, deliveries, and invoices.": "收货、交付与发票含批次、保质期与效期。",
        "Approval Workflows": "审批工作流",
        "Tier validation on sales, purchases, stock moves, and invoices.": "销售、采购、库存移动与发票分级校验。",
        "Chemical Product Catalog": "化工产品目录",
        "COO, manufacturer, business unit, and strategic BU on products.": "产品含原产国、制造商、业务单元与战略 BU。",
        "Customer Trade Profiles": "客户贸易档案",
        "Grading, segments, credit limits, and trade vs non-trade routing.": "分级、细分、信用额度与贸易/非贸易路由。",
        "Indent &amp; Ex-Stock Sales": "订货与现货销售",
        "Order types with RCC partners, agency fees, and shipping data.": "订单类型含 RCC 伙伴、代理费与装运数据。",
        "Price &amp; Margin Approval": "价格与毛利审批",
        "VOC, min selling price, and blocked quote send until approved.": "VOC、最低售价与未审批禁止发送报价。",
        "Shelf-Life Enforcement": "保质期强制",
        "GR validation when batch shelf-life conflicts are detected.": "检测批次保质期冲突时 GR 校验。",
        "Landed Cost Allocation": "到岸成本分摊",
        "Import cost splits by business unit onto chemical batches.": "进口成本按业务单元分摊至化工批次。",
        "Branded Trade Documents": "品牌贸易文档",
        "Invoices with lot/expiration lines, delivery notes, and statements.": "发票含批次/效期行、送货单与对账单。",
        "Website Quote Requests": "网站询价",
        "eCommerce catalog with grouped products and quote checkout.": "eCommerce 目录含分组产品与询价结账。",
        "Quote &amp;": "报价与",
        "Approve": "审批",
        "Build quotation with margin checks and tier validation sign-off": "构建含毛利检查与分级审批签字的报价",
        "Order &amp;": "下单与",
        "Source": "寻源",
        "Confirm indent purchase or ex-stock allocation with shipping terms": "确认订货采购或现货分配含装运条款",
        "Receive &amp;": "收货与",
        "Cost": "成本",
        "Goods receipt with shelf-life checks and landed cost posting": "收货含保质期检查与到岸成本过账",
        "Deliver &amp;": "交付与",
        "Ship with lot traceability and print branded trade invoices": "发货含批次追溯并打印品牌贸易发票",
        "Monitor &amp;": "监控与",
        "Report": "报表",
        "Track credit, slow movers, commissions, and AR aging": "跟踪信用、滞销、佣金与应收账龄",
        "Route orders by stock strategy and import sourcing rules": "按库存策略与进口寻源规则路由订单",
        "Trade, non-trade, agency, and RCC partner classifications": "贸易、非贸易、代理与 RCC 伙伴分类",
        "Credit limit and available limit by customer grading": "按客户分级信用额度与可用额度",
        "Purchase blocks and flagged sales lines on aged inventory": "账龄库存采购冻结与标记销售行",
        "Business unit and strategic BU distribution on lines": "行级业务单元与战略 BU 分配",
        "Contact approval before transactions": "交易前联系人审批",
        "Split deliveries by line delivery dates": "按行交付日期拆分交付",
        "Sales contract generation from DOCX": "从 DOCX 生成销售合同",
        "Purchase-from-sale for indent sourcing": "订货寻源按销售采购",
        "Trade interest, VAT, and lead time reports": "贸易利息、VAT 与交期报表",
        "Slow-moving and shelf-life alerts": "滞销与保质期预警",
        "Consignee and notify party on deliveries": "交付含收货人与通知方",
        "Agency fee and commission sale handling": "代理费与佣金销售处理",
        "Indent (156) 63%": "订货 (156) 63%",
        "Ex-Stock (92) 37%": "现货 (92) 37%",
        "Quotations": "报价",
        "Indents": "订货",
        "Trade Ops": "贸易运营",
        "Shelf Life": "保质期",
        "Credit": "信用",
        "Coatings": "涂料",
        "Home Care": "家居护理",
        "Food Sci": "食品科学",
        "Personal": "个人护理",
        "Issue": "问题",
        "SO-3921": "SO-3921",
        "Paints Co.": "涂料公司",
        "Margin": "毛利",
        "SO-3928": "SO-3928",
        "Care Brands": "护理品牌",
        "Limit": "额度",
        "SO-3934": "SO-3934",
        "BuildChem": "BuildChem",
        "Tier 2": "二级",
        "Approval": "审批",
        "SO-3939": "SO-3939",
        "Food Ing.": "食品原料",
        "Price": "价格",
        "Controlled Quoting": "受控报价",
        "Margin and credit rules before orders reach the warehouse.": "订单到仓前执行毛利与信用规则。",
        "Import Cost Clarity": "进口成本清晰",
        "Landed costs allocated to the right business unit and batch.": "到岸成本分摊至正确业务单元与批次。",
        "Batch Integrity": "批次完整性",
        "Shelf-life and lot data carried through to customer invoices.": "保质期与批次数据延续至客户发票。",
        "Governed Operations": "受控运营",
        "Approvals on sales, purchases, deliveries, and billing.": "销售、采购、交付与开票审批。",
    },
    "school-uniform-seller": {
        "Alitec's School Uniform Seller solution on Odoo helps uniform retailers, school shops, and appointed vendors manage every step of the operation, from online ordering and POS sales to inventory, purchasing, invoicing, payments, pickup, and delivery.":
            "Alitec 校服销售 Odoo 方案帮助校服零售商、校内店与指定供应商管理全流程，从在线订购与 POS 销售到库存、采购、开票、支付、自提与配送。",
        "Alitec's School Uniform Seller solution on Odoo helps uniform retailers,\n        school shops, and appointed vendors manage every step of the operation,\n        from online ordering and POS sales to inventory, purchasing, invoicing,\n        payments, pickup, and delivery.":
            "Alitec 校服销售 Odoo 方案帮助校服零售商、校内店与指定供应商管理全流程，从在线订购与 POS 销售到库存、采购、开票、支付、自提与配送。",
        "School Uniform<br />Seller": "校服<br />销售",
        "School Uniform": "校服",
        "Seller": "销售",
        "Online / POS<br />Order": "在线 / POS<br />订购",
        "Student<br />Details": "学生<br />信息",
        "Pick &amp;<br />Pack": "拣货与<br />包装",
        "Invoice &amp;<br />Payment": "开票与<br />支付",
        "Collect /<br />Deliver": "自提 /<br />配送",
        "Complete Uniform Retail Solutions with Odoo": "完整校服零售 Odoo 方案",
        "Uniform Sales Workflow": "校服销售工作流",
        "Term Sale": "学期销售",
        "Preorder": "预订",
        "Collection": "自提",
        "Exchange": "换货",
        "Schools": "学校",
        "Uniform SKUs": "校服 SKU",
        "Online Orders": "在线订单",
        "Pickup Slots": "自提时段",
        "Stock Accuracy": "库存准确率",
        "Order Channel Overview": "订单渠道概览",
        "Monthly Uniform Revenue": "月度校服收入",
        "Order Channel Mix": "订单渠道构成",
        "Orders Awaiting Fulfilment": "待履约订单",
        "Centralized": "集中化",
        "School, student, sales, stock, and finance data together.": "学校、学生、销售、库存与财务数据一体化。",
        "Omnichannel": "全渠道",
        "Run website, POS, quote, and office orders from one catalog.": "从统一目录运行网站、POS、报价与办公室订单。",
        "Accurate": "精准",
        "Track variants, stock, orders, invoices, and payments.": "跟踪变体、库存、订单、发票与支付。",
        "Scalable": "可扩展",
        "Support seasons, preorders, promotions, replenishment, and reports.": "支持学期、预订、促销、补货与报表。",
        "School &amp; Student Profiles": "学校与学生档案",
        "Capture school, class, student name, and order references.": "采集学校、班级、学生姓名与订单参考。",
        "Uniform Catalog &amp; Variants": "校服目录与变体",
        "Manage shirts, PE kits, sizes, bundles, combos, and pricing.": "管理衬衫、体育服、尺码、套装、组合与定价。",
        "Website &amp; POS Sales": "网站与 POS 销售",
        "Sell online or in-store with wishlist, loyalty, and stock checks.": "在线或门店销售，含心愿单、积分与库存检查。",
        "Sales &amp; Invoicing": "销售与开票",
        "Create orders, invoices, FAS documents, delivery slips, and notes.": "创建订单、发票、FAS 文档、送货单与备注。",
        "Inventory &amp; Replenishment": "库存与补货",
        "Monitor stock by location, availability, and weekly alerts.": "按库位、可用性与周预警监控库存。",
        "Purchase &amp; Supplier Flow": "采购与供应商流程",
        "Plan procurement, track picking status, and select products fast.": "计划采购、跟踪拣货状态并快速选品。",
        "Pickup, Delivery &amp; Shipping": "自提、配送与发货",
        "Configure pickup slots, carriers, SingPost, Shippit, and tracking.": "配置自提时段、承运商、SingPost、Shippit 与跟踪。",
        "Reports &amp; Analytics": "报表与分析",
        "Review sales, stock movement, payments, periods, and performance.": "审阅销售、库存移动、支付、期间与绩效。",
        "Online / POS": "在线 / POS",
        "Order": "订购",
        "Parent, counter, or back-office sale": "家长、柜台或后台销售",
        "Student": "学生",
        "Details": "信息",
        "School, class, name, and references": "学校、班级、姓名与参考",
        "Pick &amp;": "拣货与",
        "Pack": "包装",
        "Variant stock from warehouse or shop": "从仓库或门店拣选变体库存",
        "Invoice &amp;": "开票与",
        "Payment": "支付",
        "Invoice, PayNow, cards, and gateways": "发票、PayNow、银行卡与支付网关",
        "Collect /": "自提 /",
        "Deliver": "配送",
        "Pickup slot, carrier delivery, tracking": "自提时段、承运配送、跟踪",
        "Back-to-school demand": "开学季需求",
        "Seasonal stock planning": "季节性库存计划",
        "Appointment-based pickup": "预约自提",
        "Carrier shipping flow": "承运发货流程",
        "Controlled replacement orders": "受控换货订单",
        "Product / Variant Control": "产品/变体管控",
        "Replenishment Reminders": "补货提醒",
        "Payment Notifications": "支付通知",
        "Product / Unit Replacement": "产品/单位换货",
        "Online Parent Portal": "在线家长门户",
        "Sales &amp; Stock Reports": "销售与库存报表",
        "Custom Print Templates": "定制打印模板",
        "Accounting Integration": "财务集成",
        "Website (232) 63%": "网站 (232) 63%",
        "POS / Walk-in (136) 37%": "POS / 到店 (136) 37%",
        "White Shirts": "白衬衫",
        "PE Sets": "体育服套装",
        "Blazers": "西装外套",
        "Accessories": "配饰",
        "SO-1842": "SO-1842",
        "North Pri": "北部小学",
        "East Sec": "东部中学",
        "West Pri": "西部小学",
        "Central": "中部",
        "Sell Across Every Channel": "全渠道销售",
        "Operate web, POS, quotations, and school campaigns without duplicate data entry.": "网站、POS、报价与学校活动无需重复录入。",
        "Better Stock Visibility": "更好库存可视化",
        "Know available stock, reserved items, supplier needs, and fulfilment status faster.": "更快掌握可用库存、预留、供应商需求与履约状态。",
        "Cleaner Finance Flow": "更清晰财务流程",
        "Connect orders, invoices, DBS QR, online gateways, receipts, and reconciliation.": "贯通订单、发票、DBS QR、在线网关、收据与对账。",
        "Parent Satisfaction": "家长满意度",
        "Simpler ordering, pickup slots, delivery tracking, accurate documents, and fast service.": "更简单订购、自提时段、配送跟踪、准确文档与快速服务。",
    },
    "corporate-hamper-gifting": {
        "Alitec's corporate gifting solution lets customers buy many hampers in one checkout — each with its own delivery address, shipping date, and greeting message — while your team fulfils, invoices, and delivers from one Odoo platform.":
            "Alitec 企业礼品方案让客户一次结账购买多份礼盒 — 每份独立配送地址、发货日期与贺卡留言 — 团队在同一 Odoo 平台履约、开票与配送。",
        "Alitec's corporate gifting solution lets customers buy many hampers in one checkout —\n        each with its own delivery address, shipping date, and greeting message — while your\n        team fulfils, invoices, and delivers from one Odoo platform.":
            "Alitec 企业礼品方案让客户一次结账购买多份礼盒 — 每份独立配送地址、发货日期与贺卡留言 — 团队在同一 Odoo 平台履约、开票与配送。",
        "Corporate Hamper<br />Gifting": "企业礼盒<br />馈赠",
        "Corporate Hamper": "企业礼盒",
        "Gifting": "馈赠",
        "Multi-Recipient Delivery — eCommerce, Counter Sales &amp; Gifting with Odoo": "多收件人配送 — eCommerce、柜台销售与礼品",
        "Gifting Workflow": "礼品工作流",
        "Shop or<br />Sell": "选购或<br />销售",
        "Assign<br />Recipients": "指定<br />收件人",
        "Pay<br />Once": "一次<br />支付",
        "Deliver<br />Gifts": "配送<br />礼品",
        "Per-Line Address": "按行地址",
        "Shipping Date": "发货日期",
        "Greeting Card": "贺卡",
        "Pickup Method": "取货方式",
        "Blocked Dates": "不可选日期",
        "Multi-Delivery Orders": "多地址订单",
        "Due Today": "今日到期",
        "Greetings Pending": "待写贺卡",
        "Counter Orders": "柜台订单",
        "Web Orders": "网站订单",
        "Channel Mix": "渠道构成",
        "Weekly Gift Orders": "周礼品订单",
        "Deliveries by Date": "按日期配送",
        "Hampers to Pack Today": "今日待包装礼盒",
        "One Checkout, Many Gifts": "一次结账，多份礼品",
        "Assign a different recipient and date to every hamper line.": "每行礼盒指定不同收件人与日期。",
        "Greeting Messages": "贺卡留言",
        "Card recipient, sender, and greeting carried to fulfilment.": "贺卡收件人、寄件人与留言延续至履约。",
        "Counter Quick Sale": "柜台快速销售",
        "Cash-and-carry roadshow flow with receipt printing and pricelists.": "现金提货路演流程含收据打印与价目表。",
        "Smart Delivery Fees": "智能配送费",
        "Shipping costs calculated per address and hamper quantity.": "按地址与礼盒数量计算运费。",
        "Multi-Address Checkout": "多地址结账",
        "Website cart with per-line delivery recipient and date.": "网站购物车按行指定收件人与日期。",
        "Greeting Card Fields": "贺卡字段",
        "Recipient, sender, greeting, and delivery note on each gift.": "每份礼品含收件人、寄件人、留言与配送备注。",
        "Greeting Templates": "贺卡模板",
        "Pre-fill message templates for faster online ordering.": "预填留言模板加速在线订购。",
        "Pricelist Control": "价目表管控",
        "Default pricelists for counter quick-sale and standard sales.": "柜台快销与标准销售默认价目表。",
        "Roadshow orders with cash-and-carry and payment journals.": "路演订单含现金提货与付款日记账。",
        "Pickup Options": "取货选项",
        "Cash &amp; carry, self collection, or ship-to-recipient delivery.": "现金提货、自提或配送给收件人。",
        "Split Fulfilment": "拆分履约",
        "One order generates multiple deliveries by address and date.": "一单按地址与日期生成多笔交付。",
        "Shop or": "选购或",
        "Sell": "销售",
        "Order online or create a counter quick-sale with the right pricelist": "在线订购或以正确价目表创建柜台快销",
        "Assign": "指定",
        "Recipients": "收件人",
        "Set delivery address, date, and greeting on each hamper line": "每行礼盒设置地址、日期与贺卡留言",
        "Pay": "支付",
        "Once": "一次",
        "Single payment with delivery fees grouped by shipment": "一次支付，运费按发货分组",
        "Deliver": "配送",
        "Gifts": "礼品",
        "Multiple gift deliveries from one corporate order": "一笔企业订单多份礼品配送",
        "Different recipient on every hamper order line": "每行礼盒不同收件人",
        "Schedule each gift delivery on its own date": "每份礼品独立排程发货日期",
        "Recipient, sender, and message on pick documents": "拣货单含收件人、寄件人与留言",
        "Cash &amp; carry, self collect, or ship later": "现金提货、自提或稍后发货",
        "Control unavailable delivery dates on checkout": "结账管控不可配送日期",
        "Receipt printing for counter sales": "柜台销售收据打印",
        "Barcode-to-delivery wizard": "条码转交付向导",
        "Multiple terms and conditions": "多份条款条件",
        "WhatsApp customer messaging": "WhatsApp 客户消息",
        "Warehouse reporting for fulfilment": "仓库履约报表",
        "Reseller vs corporate customer rules": "经销商与企业客户规则",
        "Delivery fee per hamper quantity": "按礼盒数量计费配送",
        "Customer acknowledgment on ship-later": "稍后发货客户确认",
        "Web (168) 70%": "网站 (168) 70%",
        "Counter (72) 30%": "柜台 (72) 30%",
        "Pack Today": "今日包装",
        "Greetings": "贺卡",
        "CS Team": "客服团队",
        "Multi-Ship": "多地址发货",
        "Roadshow": "路演",
        "Next Week": "下周",
        "Recipient": "收件人",
        "Ship": "发货",
        "SO-2201": "SO-2201",
        "Acme Corp": "Acme 公司",
        "SO-2204": "SO-2204",
        "Lee &amp; Co": "李氏公司",
        "SO-2208": "SO-2208",
        "Walk-in": "到店",
        "SO-2212": "SO-2212",
        "Global Pte": "Global Pte",
        "Easier Corporate Orders": "更简单企业订购",
        "One payment, dozens of personalised gift deliveries.": "一次支付，数十份个性化礼品配送。",
        "Personal Touch at Scale": "规模化个性关怀",
        "Greeting messages on every hamper without spreadsheets.": "每份礼盒贺卡留言，无需电子表格。",
        "Omnichannel Selling": "全渠道销售",
        "Same catalogue online and at counter quick-sale events.": "在线与柜台快销活动同一目录。",
        "Cleaner Fulfilment": "更清晰履约",
        "Addresses and dates drive automatic delivery splits.": "地址与日期驱动自动交付拆分。",
    },
    "pet-food-accessories-ecommerce": {
        "Alitec's pet retail eCommerce solution helps premium online stores sell food and accessories, capture pet member profiles, run loyalty and referral programmes, bundle products on the website, and fulfil orders with local shipping — all in one Odoo platform.":
            "Alitec 宠物零售电商方案帮助高端在线商店销售食品与用品、采集宠物会员档案、运行积分与推荐计划、网站套装销售并以本地物流履约 — 统一于 Odoo 平台。",
        "Alitec's pet retail eCommerce solution helps premium online stores sell food and accessories,\n        capture pet member profiles, run loyalty and referral programmes, bundle products on the\n        website, and fulfil orders with local shipping — all in one Odoo platform.":
            "Alitec 宠物零售电商方案帮助高端在线商店销售食品与用品、采集宠物会员档案、运行积分与推荐计划、网站套装销售并以本地物流履约 — 统一于 Odoo 平台。",
        "Pet Food &amp;<br />Accessories eCommerce": "宠物食品与<br />用品电商",
        "Pet Food &amp;": "宠物食品与",
        "Accessories eCommerce": "用品电商",
        "Premium Online Retail — Loyalty, Bundles &amp; Fulfilment with Odoo": "高端在线零售 — 积分、套装与履约",
        "Retail Workflow": "零售工作流",
        "Join &amp;<br />Register": "加入与<br />注册",
        "Shop<br />Online": "在线<br />选购",
        "Pick &amp;<br />Pack": "拣货与<br />包装",
        "Ship &amp;<br />Track": "发货与<br />跟踪",
        "Pet Types": "宠物类型",
        "Loyalty Rules": "积分规则",
        "Referrals": "推荐",
        "Bundles": "套装",
        "Shipping": "物流",
        "Web Orders Today": "今日网站订单",
        "Active Members": "活跃会员",
        "Loyalty Redeemed": "已兑换积分",
        "Ship Today": "今日发货",
        "Category Mix": "品类构成",
        "Weekly Web Revenue": "周网站收入",
        "Top Category Sales": "热门品类销售",
        "Orders Awaiting Dispatch": "待发货订单",
        "Pet Member Profiles": "宠物会员档案",
        "Register cats and dogs with breed, birthday, and owner details at signup.": "注册时登记猫狗品种、生日与主人信息。",
        "Loyalty &amp; Referrals": "积分与推荐",
        "Signup points, refer-a-friend codes, and shop redemption at checkout.": "注册积分、推荐好友码与结账兑换。",
        "Premium Web Store": "高端网店",
        "Theme Prime storefront with brands, bundles, wishlist, and mobile shopping.": "Theme Prime 店面含品牌、套装、心愿单与移动购物。",
        "Local Fulfilment": "本地履约",
        "EasyParcel labels, tracking, and shipping updates after order confirmation.": "EasyParcel 面单、跟踪与确认后物流更新。",
        "Pet Member Data": "宠物会员数据",
        "Pet lines with name, breed, type, and DOB on partners and portal.": "合作伙伴与门户宠物行含名称、品种、类型与生日。",
        "Member Registration": "会员注册",
        "Public signup form with PDPA consent and acquisition source tracking.": "公开注册表单含 PDPA 同意与获客来源跟踪。",
        "Premium eCommerce": "高端 eCommerce",
        "Theme Prime shop with brands, filters, quick view, and comparison.": "Theme Prime 商店含品牌、筛选、快速查看与对比。",
        "Product Bundles": "产品套装",
        "Sell food and accessory kits across web, sales, stock, and invoices.": "网站、销售、库存与发票销售食品与用品套装。",
        "Loyalty Programmes": "积分计划",
        "Signup rewards, promotion rules, limits, and multi-product criteria.": "注册奖励、促销规则、上限与多产品条件。",
        "Refer &amp; Earn": "推荐有礼",
        "Referral codes, friend signup points, and discount redemption online.": "推荐码、好友注册积分与在线折扣兑换。",
        "EasyParcel Shipping": "EasyParcel 物流",
        "Rates, labels, tracking, and post-confirm carrier changes on pickings.": "费率、面单、跟踪与确认后承运商变更。",
        "Stripe + PayNow": "Stripe + PayNow",
        "Card checkout with Singapore PayNow on the web payment flow.": "网站支付流程支持银行卡与新加坡 PayNow。",
        "Join &amp;": "加入与",
        "Member signup with pet profiles, consent, and signup loyalty points": "会员注册含宠物档案、同意书与注册积分",
        "Shop": "选购",
        "Browse brands, bundles, wishlist, and apply loyalty rewards at checkout": "浏览品牌、套装、心愿单并在结账使用积分",
        "Pay": "支付",
        "Securely": "安全",
        "Stripe card payment with PayNow for Singapore customers": "新加坡客户 Stripe 卡支付与 PayNow",
        "Ship &amp;": "发货与",
        "Track": "跟踪",
        "EasyParcel labels, tracking links, and branded order documents": "EasyParcel 面单、跟踪链接与品牌订单文档",
        "Cat and dog profiles with breed and birthday on member accounts": "会员账户猫狗档案含品种与生日",
        "Exclude shipping from points and cap promotions per customer": "积分不含运费并限制每客户促销",
        "Friend codes, signup credits, and shop discount redemption": "好友码、注册额度与商店折扣兑换",
        "Combo packs for food, treats, and grooming accessories online": "在线食品、零食与美容用品组合装",
        "Change carrier on confirmed orders before pickings complete": "拣货完成前可更改已确认订单承运商",
        "Branded sales and invoice PDF layouts": "品牌销售与发票 PDF 版式",
        "Portal pet management for members": "会员门户宠物管理",
        "Wishlist and product comparison on shop": "商店心愿单与产品对比",
        "Acquisition source tracking on signup": "注册获客来源跟踪",
        "PDPA and marketing consent capture": "PDPA 与营销同意采集",
        "Promotion start dates and loyalty limits": "促销开始日期与积分上限",
        "Smart warnings on sales documents": "销售文档智能预警",
        "Stock-aware web catalog and reporting": "库存感知网店目录与报表",
        "4.2k": "4.2k",
        "Pet Food (64%) 218": "宠物食品 (64%) 218",
        "Accessories (36%) 124": "用品 (36%) 124",
        "Loyalty": "积分",
        "Web Orders": "网站订单",
        "Fulfilment": "履约",
        "Dog Food": "狗粮",
        "Cat Food": "猫粮",
        "Grooming": "美容",
        "SO-2842": "SO-2842",
        "L. Tan": "L. Tan",
        "SO-2847": "SO-2847",
        "M. Lee": "M. Lee",
        "Bundle": "套装",
        "SO-2851": "SO-2851",
        "K. Wong": "K. Wong",
        "SO-2854": "SO-2854",
        "S. Lim": "S. Lim",
        "Accessories": "用品",
        "Know Every Pet": "了解每只宠物",
        "Member profiles with breed and birthday for personalised retail.": "会员档案含品种与生日，支持个性化零售。",
        "Rewards That Retain": "留住客户的积分",
        "Loyalty and referral programmes built into the web checkout.": "积分与推荐计划内置网站结账。",
        "Premium Storefront": "高端店面",
        "Brands, bundles, and stock-aware shopping in one catalog.": "品牌、套装与库存感知购物同一目录。",
        "Click to Doorstep": "点击到门",
        "Orders, pickings, EasyParcel labels, and tracking in Odoo.": "订单、拣货、EasyParcel 面单与跟踪在 Odoo。",
    },
    "scaffolding": {
        "<strong>Manage rental orders, site deliveries, returns, claims, and billing in one platform.</strong> Alitec's scaffolding solution on Odoo connects rental quotations, customer POs, rental orders, deliveries, returns, repair and lost charges, project claims, intercompany warehouse movement, and statement of account generation.":
            "<strong>在一个平台管理租赁订单、现场交付、归还、索赔与开票。</strong> Alitec 脚手架 Odoo 方案贯通租赁报价、客户 PO、租赁订单、交付、归还、维修与丢失费用、项目索赔、跨公司仓库调拨与对账单生成。",
        "Scaffolding Rental &amp;<br />Project Claims": "脚手架租赁与<br />项目索赔",
        "Scaffolding Rental &amp;": "脚手架租赁与",
        "Project Claims": "项目索赔",
        "End-to-End Rental, Warehouse, Project and Billing Control with Odoo": "端到端租赁、仓库、项目与开票管控",
        "Manage rental orders, site deliveries, returns, claims, and billing in one platform.": "在一个平台管理租赁订单、现场交付、归还、索赔与开票。",
        "Alitec's scaffolding solution on Odoo connects rental quotations, customer POs,\n        rental orders, deliveries, returns, repair and lost charges, project claims,\n        intercompany warehouse movement, and statement of account generation.":
            "Alitec 脚手架 Odoo 方案贯通租赁报价、客户 PO、租赁订单、交付、归还、维修与丢失费用、项目索赔、跨公司仓库调拨与对账单生成。",
        "Rental Quotation": "租赁报价",
        "Customer PO": "客户 PO",
        "Rental Order": "租赁订单",
        "Delivery / Return": "交付 / 归还",
        "Claim / Invoice": "索赔 / 开票",
        "Active Rental Orders": "活跃租赁订单",
        "Open Project Claims": "开放项目索赔",
        "Items in Rental": "在租物料",
        "Pending Returns": "待归还",
        "Monthly Billing": "月度开票",
        "Rental Status": "租赁状态",
        "Monthly Billing Trend": "月度开票趋势",
        "Rental Order Flow": "租赁订单流程",
        "Quotation, customer PO, rental order, return, and recurring billing stay linked.": "报价、客户 PO、租赁订单、归还与周期性开票保持关联。",
        "Delivery Control": "交付管控",
        "Track site dispatches, returns, repair, loss, and over-return handling.": "跟踪现场发运、归还、维修、丢失与超还处理。",
        "Manage work done, dismantling records, claims, and certificates.": "管理工程量、拆除记录、索赔与证书。",
        "Billing Visibility": "开票可视化",
        "Support rental billing by density, delivery percentage, and monthly cycles.": "支持按密度、交付比例与月度周期的租赁开票。",
        "1. Rental Order Flow": "1. 租赁订单流程",
        "Quotation, customer PO, rental order, delivery, return, and recurring billing.": "报价、客户 PO、租赁订单、交付、归还与周期性开票。",
        "2. Delivery &amp; Return Control": "2. 交付与归还管控",
        "Track site dispatches, return balances, repair, loss, and over-return handling.": "跟踪现场发运、归还余额、维修、丢失与超还处理。",
        "3. Project Claims": "3. 项目索赔",
        "Manage contracts, work done, erection and dismantling records, claims, and certificates.": "管理合同、工程量、搭设与拆除记录、索赔与证书。",
        "4. M3 Rental Billing": "4. 立方米租赁开票",
        "Support volume-based rental with density, delivery percentage, and monthly billing.": "支持按密度、交付比例与月度开票的体积租赁。",
        "5. New / Used Item Logic": "5. 新/旧物料逻辑",
        "Route stock from new or used locations and post revenue to the correct accounts.": "从新/旧库位调拨库存并将收入过账至正确科目。",
        "6. Intercompany Warehouse": "6. 跨公司仓库",
        "Mirror pickings across companies and keep project references aligned.": "跨公司镜像拣货并保持项目参考一致。",
        "Business Process Flow": "业务流程",
        "Structure your scaffolding operations in a clear operational sequence.": "以清晰运营顺序组织脚手架业务。",
        "Pricing, rental rates, project reference": "定价、租赁费率、项目参考",
        "Confirm requested quantities": "确认需求数量",
        "Delivery planning and billing basis": "交付计划与计费基础",
        "Site movement, balance tracking, repair/loss": "现场移动、余额跟踪、维修/丢失",
        "Rental billing, project claims, SOA": "租赁开票、项目索赔、对账单",
        "Control quantities by delivery and return.": "按交付与归还管控数量。",
        "Link rental activity to project codes.": "将租赁活动关联项目编码。",
        "Reduce billing leakage and manual tracking.": "减少开票流失与手工跟踪。",
        "Improve warehouse and finance coordination.": "改善仓库与财务协同。",
        "Operations Dashboard Overview": "运营仪表盘概览",
        "Get a real-time view of rental, project, stock, and billing activity.": "实时查看租赁、项目、库存与开票活动。",
        "5,320": "5,320",
        "$368K": "$368K",
        "On Rent 64.3%": "在租 64.3%",
        "Available 23.5%": "可用 23.5%",
        "Repair / Lost 12.2%": "维修/丢失 12.2%",
        "Recent Projects": "近期项目",
        "Claim Status": "索赔状态",
        "Billing": "开票",
        "Downtown Tower": "市中心大厦",
        "Commercial": "商业",
        "Approved": "已批准",
        "$92,400": "$92,400",
        "Metro Line Extension": "地铁延伸线",
        "Infrastructure": "基础设施",
        "$78,600": "$78,600",
        "Industrial Plant Expansion": "工厂扩建",
        "$64,800": "$64,800",
        "Harbor Warehouse": "港口仓库",
        "$48,900": "$48,900",
        "Residential Complex A": "住宅综合体 A",
        "$83,300": "$83,300",
        "Better Stock Visibility": "更好库存可视化",
        "Control rental balances, site stock, repair items, and return gaps.": "管控租赁余额、现场库存、维修件与归还差异。",
        "Faster Project Claims": "更快项目索赔",
        "Prepare claim documents and certificates with less manual tracking.": "更少手工跟踪即可准备索赔文档与证书。",
        "More Accurate Billing": "更准确开票",
        "Invoice rental, repair, loss, and project charges from one flow.": "从同一流程开票租赁、维修、丢失与项目费用。",
        "Stronger Coordination": "更强协同",
        "Keep sales, warehouse, project, and finance teams aligned.": "保持销售、仓库、项目与财务团队一致。",
    },
    "bakery-ecommerce-operations": {
        "Alitec's bakery solution helps cake and patisserie businesses sell online and in-store with daily production capacity control, delivery and collection scheduling, customized product options, and member loyalty in one Odoo platform.":
            "Alitec 烘焙方案帮助蛋糕与西点企业在线与门店销售，含每日产能管控、配送与自提排程、定制产品选项与会员积分 — 统一于 Odoo 平台。",
        "Alitec's bakery solution helps cake and patisserie businesses sell online\n        and in-store with daily production capacity control, delivery and collection\n        scheduling, customized product options, and member loyalty in one Odoo platform.":
            "Alitec 烘焙方案帮助蛋糕与西点企业在线与门店销售，含每日产能管控、配送与自提排程、定制产品选项与会员积分 — 统一于 Odoo 平台。",
        "Bakery E-Commerce<br />Operations": "烘焙电商<br />运营",
        "Bakery E-Commerce": "烘焙电商",
        "Cakes &amp; Cookies Online — From Web Shop to Kitchen with Odoo": "蛋糕与饼干在线 — 从网店到厨房",
        "Order Workflow": "订单工作流",
        "Shop &amp;<br />Customize": "选购与<br />定制",
        "Schedule<br />Fulfillment": "排程<br />履约",
        "Produce &amp;<br />Dispatch": "生产与<br />发运",
        "Retain<br />Members": "留住<br />会员",
        "Daily Caps": "每日上限",
        "Time Windows": "时间窗口",
        "Login Required": "需登录",
        "POS Loyalty": "POS 积分",
        "Capacity Used": "已用产能",
        "Orders Tomorrow": "明日订单",
        "Coupons Used": "已用优惠券",
        "Fulfillment Mix": "履约构成",
        "Weekly Order Volume": "周订单量",
        "Capacity by Category": "按品类产能",
        "Upcoming Fulfillment": "即将履约",
        "Never Oversell": "绝不超卖",
        "Category daily maximums block orders when the kitchen is already full.": "品类每日上限在厨房已满时阻止下单。",
        "Smart Slots": "智能时段",
        "Delivery, collection, holidays, and delicate-product time rules stay aligned.": "配送、自提、节假日与精致产品时段规则保持一致。",
        "Member Loyalty": "会员积分",
        "Paid memberships auto-issue coupons and tiered pricing online and in-store.": "付费会员自动发放优惠券与分级定价，线上线下通用。",
        "Kitchen Reports": "厨房报表",
        "Daily kitchen lists and delivery or collection reports drive production.": "每日厨房清单与配送/自提报告驱动生产。",
        "Online Bakery Shop": "在线烘焙店",
        "Sell cakes and patisserie products with stock-aware e-commerce.": "库存感知 eCommerce 销售蛋糕与西点。",
        "Delivery or Collection": "配送或自提",
        "Support home delivery and outlet self-collection with carrier rules.": "支持送货上门与门店自提，含承运规则。",
        "Date &amp; Time Booking": "日期与时间预约",
        "Let customers choose fulfillment dates and time slots at checkout.": "结账时让客户选择履约日期与时段。",
        "Daily Capacity Control": "每日产能管控",
        "Manage production limits by product category and order date.": "按产品品类与订单日期管理产能上限。",
        "Blocked Dates": "封锁日期",
        "Stop orders on holiday blackout days and full-capacity dates.": "节假日与满产能日期停止接单。",
        "Custom Product Options": "定制产品选项",
        "Handle variants and product options for customized cake orders.": "处理定制蛋糕订单的变体与选项。",
        "Membership &amp; Coupons": "会员与优惠券",
        "Issue annual or lifetime membership rewards automatically.": "自动发放年度或终身会员奖励。",
        "Export kitchen lists and delivery or collection run sheets.": "导出厨房清单与配送/自提运行表。",
        "Customize": "定制",
        "Logged-in customers choose products, variants, and options": "登录客户选择产品、变体与选项",
        "Fulfillment": "履约",
        "Pick delivery or collection, date, and time slot": "选择配送或自提、日期与时段",
        "Checkout validates capacity before payment completes": "支付完成前校验产能",
        "Dispatch": "发运",
        "Kitchen lists and fulfillment reports drive daily work": "厨房清单与履约报告驱动每日工作",
        "Members": "会员",
        "Coupons, tiers, and birthday offers bring customers back": "优惠券、等级与生日优惠促进复购",
        "Category production limits by date": "按日期品类产能上限",
        "Meringue and non-meringue slot rules": "蛋白霜与非蛋白霜时段规则",
        "Cart and checkout for registered customers": "注册用户购物车与结账",
        "Auto coupons and tiered pricing": "自动优惠券与分级定价",
        "Redeem rewards in-store and online": "门店与线上兑换奖励",
        "Made-to-order lead times": "按单生产提前期",
        "Branded invoice and delivery docs": "品牌发票与交付文档",
        "Portal membership and coupons": "门户会员与优惠券",
        "Birthday-month notifications": "生日月通知",
        "Holiday blackout dates": "节假日封锁日期",
        "Collection outlet addresses": "自提门店地址",
        "Payment gateway support": "支付网关支持",
        "Kitchen ordered list export": "厨房排序清单导出",
        "Collection (142) 58%": "自提 (142) 58%",
        "Delivery (103) 42%": "配送 (103) 42%",
        "Daily Capacity": "每日产能",
        "Kitchen": "厨房",
        "Tomorrow Orders": "明日订单",
        "Planning": "计划",
        "Member Coupons": "会员优惠券",
        "Cakes": "蛋糕",
        "Cookies": "饼干",
        "Meringue": "蛋白霜",
        "SO-1042": "SO-1042",
        "Custom Cake": "定制蛋糕",
        "10:30": "10:30",
        "SO-1048": "SO-1048",
        "Cookie Box": "饼干礼盒",
        "11:00": "11:00",
        "SO-1051": "SO-1051",
        "Celebration Cake": "庆典蛋糕",
        "11:30": "11:30",
        "SO-1056": "SO-1056",
        "Assorted Pastries": "什锦西点",
        "12:00": "12:00",
        "Sell Without Overbooking": "不超卖销售",
        "Match online demand to real daily bakery production capacity.": "将在线需求匹配真实每日烘焙产能。",
        "Better Scheduling": "更好排程",
        "Give buyers clear delivery and collection date and time choices.": "为买家提供清晰的配送与自提日期时间选择。",
        "Stronger Retention": "更强留存",
        "Connect website and POS loyalty in one membership program.": "网站与 POS 积分纳入同一会员计划。",
        "Smoother Kitchen Ops": "更顺畅厨房运营",
        "Turn confirmed orders into date-based production and run sheets.": "将确认订单转为按日生产与运行表。",
    },
    "lab-testing-process": {
        "Alitec's lab testing solution helps aquaculture service providers manage farmers, field samples, five test types, treatment recommendations, and branded reports in one Odoo platform — from sample intake to billing.":
            "Alitec 实验室检测方案帮助水产服务商管理养殖户、现场样品、五类检测、处理建议与品牌报告 — 从样品接收到开票，统一于 Odoo 平台。",
        "Alitec's lab testing solution helps aquaculture service providers\n        manage farmers, field samples, five test types, treatment recommendations,\n        and branded reports in one Odoo platform — from sample intake to billing.":
            "Alitec 实验室检测方案帮助水产服务商管理养殖户、现场样品、五类检测、处理建议与品牌报告 — 从样品接收到开票，统一于 Odoo 平台。",
        "Lab Testing<br />Process": "实验室检测<br />流程",
        "Lab Testing": "实验室检测",
        "Process": "流程",
        "Aquaculture Testing — From Sample to Solution with Odoo": "水产检测 — 从样品到方案",
        "Lab Workflow": "实验室工作流",
        "Register &amp;<br />Sample": "登记与<br />采样",
        "Order<br />Tests": "下单<br />检测",
        "Run<br />Lab": "运行<br />实验",
        "Recommend<br />Treatments": "推荐<br />处理",
        "Deliver &amp;<br />Bill": "交付与<br />开票",
        "Sample Traceability": "样品追溯",
        "Multi-Sample Orders": "多样品订单",
        "Six-Stage Lab Flow": "六阶段实验流程",
        "Prescription Push": "处方推送",
        "Report Output": "报告输出",
        "Open Lab Tests": "开放检测",
        "Samples This Month": "本月样品",
        "Avg Turnaround": "平均周转",
        "PCR Completed": "PCR 完成",
        "Prescription Rate": "处方率",
        "Tests by Type": "按类型检测",
        "Monthly Sample Intake": "月度样品接收",
        "Test Category Mix": "检测类别构成",
        "Tests Awaiting Review": "待审核检测",
        "Farmer-Linked Samples": "关联养殖户样品",
        "Register farmers with district, cluster, farm, and pond context for every batch.": "每批次登记养殖户含区域、集群、养殖场与池塘信息。",
        "Auto Lab Creation": "自动创建实验",
        "Confirmed sales orders open the correct water, soil, seed, PCR, or microbiology tests.": "确认销售订单自动开启对应水质、土壤、种苗、PCR 或微生物检测。",
        "Range-Based Control": "范围管控",
        "Maintain parameter libraries with optimum values for consistent interpretation.": "维护参数库含最佳值以一致解读。",
        "Prescription Upsell": "处方增销",
        "Convert completed recommendations into quotation options for treatment products.": "将完成建议转为处理产品报价选项。",
        "Farmer &amp; Sample Registry": "养殖户与样品登记",
        "Track farmers, species, membership, and sample batches with farm and pond detail.": "跟踪养殖户、物种、会员与样品批次含农场池塘明细。",
        "Five Lab Test Types": "五类实验室检测",
        "Run water, soil, seed quality, PCR diagnostics, and microbiology workflows.": "运行水质、土壤、种苗质量、PCR 诊断与微生物流程。",
        "Sales-Triggered Testing": "销售触发检测",
        "Create lab jobs automatically when test products are sold and confirmed.": "检测产品销售确认后自动创建实验作业。",
        "Parameter Libraries": "参数库",
        "Configure test parameters, optimum ranges, and default panels for faster entry.": "配置检测参数、最佳范围与默认面板加速录入。",
        "Plankton &amp; PCR Support": "浮游生物与 PCR 支持",
        "Handle plankton analysis and flexible PCR disease panel setup in lab work.": "实验工作支持浮游生物分析与灵活 PCR 疾病面板。",
        "Prescription Workflow": "处方工作流",
        "Attach treatment recommendations to completed tests and push them to quotations.": "将处理建议附加于完成检测并推送至报价。",
        "Branded Lab Reports": "品牌实验报告",
        "Produce customer-ready PDF outputs with lab manager and signature support.": "生成客户就绪 PDF，含实验室主管与签名。",
        "Commercial Continuity": "商务延续",
        "Connect testing to sales, inventory, membership, delivery, and invoicing.": "检测关联销售、库存、会员、交付与开票。",
        "Register &amp;": "登记与",
        "Sample": "采样",
        "Create farmer records and collect farm or pond sample batches": "创建养殖户档案并采集农场或池塘样品批次",
        "Tests": "检测",
        "Build quotations with linked samples and required test products": "构建含关联样品与所需检测产品的报价",
        "Lab": "实验",
        "Process tests through receipt, testing, review, and completion": "检测经接收、实验、审核至完成",
        "Recommend": "推荐",
        "Treatments": "处理",
        "Record prescription products based on lab findings where needed": "按需根据实验结果记录处方产品",
        "Deliver &amp;": "交付与",
        "Issue branded reports, convert options, and complete billing": "出具品牌报告、转化选项并完成开票",
        "Farm, pond, and species linked to every batch": "每批次关联农场、池塘与物种",
        "Single or multiple sample sales order handling": "单或多样品销售订单处理",
        "Structured state tracking from new to complete": "从新到完成的结构化状态跟踪",
        "Completed tests feed quotation options": "完成检测馈入报价选项",
        "Individual and combined branded PDF reports": "单独与合并品牌 PDF 报告",
        "District and cluster farmer IDs": "区域与集群养殖户 ID",
        "Species and batch traceability": "物种与批次追溯",
        "Default PCR and microbiology panels": "默认 PCR 与微生物面板",
        "Lab manager name and signature": "实验室主管姓名与签名",
        "Optimum range parameter control": "最佳范围参数管控",
        "Plankton analysis in water tests": "水质检测浮游生物分析",
        "Quick-open test actions from sales": "从销售快速开启检测",
        "Membership-aware farmer records": "感知会员的养殖户档案",
        "3.2d": "3.2 天",
        "Water &amp; Soil (214) 62%": "水质与土壤 (214) 62%",
        "PCR &amp; Micro (138) 38%": "PCR 与微生物 (138) 38%",
        "Water &amp; Soil Tests": "水质与土壤检测",
        "Lab Team": "实验室团队",
        "PCR Diagnostics": "PCR 诊断",
        "Out-of-Range Alerts": "超范围预警",
        "Prescription Options": "处方选项",
        "PCR": "PCR",
        "LT-2842": "LT-2842",
        "Pond A": "池塘 A",
        "LT-2847": "LT-2847",
        "Farm B": "养殖场 B",
        "LT-2851": "LT-2851",
        "Pond C": "池塘 C",
        "LT-2854": "LT-2854",
        "Farm D": "养殖场 D",
        "Connected Lab Operations": "贯通实验室运营",
        "Keep farmers, samples, lab work, recommendations, and billing on one platform.": "养殖户、样品、实验、建议与开票同一平台。",
        "Faster Test Launch": "更快启动检测",
        "Reduce manual setup by creating lab records directly from confirmed orders.": "从确认订单直接创建实验记录，减少手工设置。",
        "Consistent Lab Quality": "一致实验质量",
        "Standardize parameters, ranges, and report outputs across teams.": "跨团队标准化参数、范围与报告输出。",
        "Stronger Follow-Through": "更强跟进",
        "Turn lab findings into structured treatment recommendations and upsell opportunities.": "将实验发现转为结构化处理建议与增销机会。",
    },
}

def main() -> None:
    OUT.write_text(json.dumps(PROJECTS, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {OUT} ({len(PROJECTS)} projects)")


if __name__ == "__main__":
    main()
